export default Object.freeze({
  HOME: "/home",
  ABOUT: "/about",
  APPOINTMENT: "/appointment",
  CONTACT_US: "/contact-us",
  SIGNIN: "/login",
  SIGNUP: "/register",
  DASHBOARD: "/dashboard",
  BOOK: "/dashboard",
  REVIEW: "review",
  BOOKING_LIST: "booking-list",
  ORDER_LIST: "order-list",
  ADD_SERVICE: "add-service",
  MAKE_STAFF: "make-staff",
  MANAGE_SERVICES: "manage-services",
});
