export default Object.freeze({
  HOME: "/home",
  APPOINTMENT: "/appointment",
  CONTACT_US: "/contact-us",
  SIGNIN: "/login",
  SIGNUP: "/register",
  DASHBOARD: "/dashboard",
  BOOK: "/dashboard",
  BOOKING_LIST: "booking/list",
  REVIEW: "review",
  ORDER_LIST: "order/list",
  ADD_SERVICE: "add/service",
  MAKE_STAFF: "make/staff",
  MANAGE_SERVICES: "manage/services",
});
